### ISSUE TITLE
Firebase(Bolt)側の開発手順についてのDocが欲しい

### ISSUE THREAD

**Issue by tk-ozawa** [tam-bourine/club-manager#103]
`postinstall:types-gas`実行後、`build:firebase`(tsc)実行後に  `firebase`系コマンドが使えるようになるというドキュメントが欲しいと思いましたがいかがでしょうか

@shuta13

**Comment by tk-ozawa** [comment]
あと、
tsファイルを弄って`firebase`系コマンドで実行させるには、tsファイルをトランスパイルしておく必要がある為、package.json内のscripts内のfirebase系コマンドに事前にtscを走らせるようにしたほうが良いのではと思いました。
(その場合ここで必要としているDocは不要となります。)

**Comment by tk-ozawa** [comment]
「良さそう」いただきました

**Comment by chiharakenta** [comment]
- アルファ版ではreadmeに追記
- ベータ版でtsc改修
↑それぞれ別issueに振り分け
