### ISSUE TITLE
創部申請シーケンス図のフォーム入力項目について

### ISSUE THREAD

**Issue by tk-ozawa** [tam-bourine/club-manager#104]
現状、創部申請時の入力必須項目に

- SlackのチャンネルID`channelID`
- 初期部員情報(members)
- 部活記事URL(Kibela URL)
- 創部理由(reason)

がありますが、部活動名も入力される必要があるのではと思ったんですがいかがでしょうか

**Comment by chiharakenta** [comment]
@tk-ozawa 
https://github.com/tam-bourine/club-manager/issues/108 一旦こっちに統一して、クローズします。
