### ISSUE TITLE
GAS 創部承認のリクエストボディーの形式変更

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#109]
**Summary/概要**
- OpenAPIの通りに修正
    - 確認方法
        - https://petstore.swagger.io/
        -  ↑こちらを開いて入力欄に `https://jsondata.okiba.me/v1/json/wtUvD210216103208` を入れる

**Goal/期待すべき完了条件**
- [x] 型定義をOpenAPI通りに変更
- [ ] OpenAPI通りのリクエストボディーを受け取れる
- [x] UUIDをGAS側で生成するコードを追加
- [x] カラム定義通りにシートに追加できる

**_How/どのようにやるか_**
club-manager チャンネルに body を載せておく

**Additional context/追記・備考**

**Comment by chiharakenta** [comment]
https://github.com/tam-bourine/club-manager/pull/121 がマージされたら着手

**Comment by shuta13** [comment]
OpenAPI の修正は完了

**Comment by chiharakenta** [comment]
シート追加と整合性合わせるのがちょっと大変そう
