### ISSUE TITLE
Bolt 創部承認のリクエストボディーの形式変更

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#110]
**Summary/概要**
- OpenAPIの通りに修正
    - 確認方法
        - https://petstore.swagger.io/
        -  ↑こちらを開いて入力欄に `https://jsondata.okiba.me/v1/json/wtUvD210216103208` を入れる

**Goal/期待すべき完了条件**
- [ ] 定めたOpenAPI通りのリクエストボディーを送るように修正

**_How/どのようにやるか_**

**Additional context/追記・備考**

**Comment by shuta13** [comment]
https://github.com/tam-bourine/club-manager/issues/157 で対応済み
