### ISSUE TITLE
BlockKit用ファイルのリファクタ

### ISSUE THREAD

**Issue by tk-ozawa** [tam-bourine/club-manager#118]
モーダルにおけるlabelと◯◯(mrkdwnなど)が必ず1:1で対応するため、関数群をもうちょい纏めたい。

_オリジナルは @tk-ozawa が https://github.com/tam-bourine/club-manager/pull/106#discussion_r575093620 にポスト_

**Comment by tk-ozawa** [comment]
スマホからやとラベルとか付けれねえ…

**Comment by 75asa** [comment]
> スマホからやとラベルとか付けれねえ…

つけれるで~
てきとーにつけといた

**Comment by tk-ozawa** [comment]
あざす！
