### ISSUE TITLE
創部申請モーダルの修正

### ISSUE THREAD

**Issue by g-nemo9** [tam-bourine/club-manager#133]
**Summary/概要**
仕様変更に伴って、創部申請モーダルを変更します。

**Goal/期待すべき完了条件**

- [x] 副部長フィールドの削除
- [x] 部費利用目的フィールドの追加
- [x] 部活動チャンネルフィールドの追加

**_How/どのようにやるか_**

**Additional context/追記・備考**

**Comment by 75asa** [comment]
@ttmone これ PR `git commit --allowd-empty 'init'` とかして PR だけ先に作っておくと吉です 🙃

**Comment by ttmone** [comment]
分岐元が大きく変更になったので、それらがマージされた後に改めてブランチ切り直そうと思っています！

**Comment by Kazu950** [comment]
@g-nemo9 
承認モーダルマージされたのでpullしてきて作業開始しても大丈夫です！
