### ISSUE TITLE
Bolt 入部申請

### ISSUE THREAD

**Issue by shuta13** [tam-bourine/club-manager#144]
**Summary/概要**
- 必要なデータ : 

**Goal/期待すべき完了条件**

- [ ] データ入力 UI の作成
- [ ] バックエンド側(GAS)に送信

**_How/どのようにやるか_**
- OpenAPI を参考に進める

**Additional context/追記・備考**
- 既存のものを参考にフォームを新たに作る
- [理想]フォームの共通化
  - button form 単位での共通化
- issueの切り分け

**Comment by tk-ozawa** [comment]
@chiharakenta @Kazu950 @g-nemo9 @shuta13 @g-nemo9 

今の入部フロー、Slackの部活チャンネルにinviteさせる処理書いてないんですけど必要そうなんで足してもいいですかね？(機能的にはすぐできそう

**Comment by 75asa** [comment]
@tk-ozawa 部活のチャネルに invit は誰をするんだっけ

**Comment by tk-ozawa** [comment]
@75asa 
入部申請者ですね

**Comment by chiharakenta** [comment]
@tk-ozawa 
> * あと、`2. 部活全件取得`のところ既に実行ユーザーが入部している部活チャンネルは取得する必要ないと思うんですがGAS上でその処理実装するの結構きつそうですかね?
>   
>   * 必要 & 実装きつそうであればβ版に挙げるのもありかなと

OpenAPIの変更を伴うので、一旦iceboxにissue作っておきます。
Bolt側は、APIから返ってきた部活をそのまま選択肢に表示しちゃって、β版でGAS側を修正するのが良いと思います。
少なくとも社員はわざわざ入部済みの部活動選ばないと思うので。

**Comment by tk-ozawa** [comment]
@chiharakenta 
ですね、一旦この案はpendingでお願いします

**Comment by chiharakenta** [comment]
issue追加しました
https://github.com/tam-bourine/club-manager/issues/198

**Comment by tk-ozawa** [comment]
@chiharakenta 
ありがとうございます!

**Comment by chiharakenta** [comment]
@shuta13 
ここiceboxに移動させてるのなんか理由ありましたっけ？（朝会自分がトイレ行ってた時に話したパターン？）
