### ISSUE TITLE
GAS創部承認時にメンバー全員が転記されるように修正

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#170]
**Summary/概要**
- GAS創部承認の動作確認
- channelIdの処理を追加したので、承認時の処理に不具合がないかどうか確認。
- 不具合がなければclose

**Goal/期待すべき完了条件**

- [ ] 創部承認用のエンドポイントを叩いて正しく動作する
    - [ ] メンバー全員が転記されるように修正

**_How/どのようにやるか_**

**Additional context/追記・備考**

**Comment by tk-ozawa** [comment]
want
- [ ] レスポンスデータに記事url, 部活名を含めていただきたいです。

**Comment by chiharakenta** [comment]
例:
```javascript
const clubName = “Among Us”;
const url = “https://tambourine.kibe.la/notes/19541”;
const userIds = [“UR285JW80”];
```
