### ISSUE TITLE
GAS創部承認時のレスポンスを修正

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#181]
**Summary/概要**
- GAS創部承認の動作確認
- channelIdの処理を追加したので、承認時の処理に不具合がないかどうか確認。
- 不具合がなければclose

**Goal/期待すべき完了条件**
- [ ] APIのレスポンスにclubのデータを含めるように変更
    - [ ] OpenAPI変更
    - [ ] ApproveModel動作変更

**_How/どのようにやるか_**

**Additional context/追記・備考**

**Comment by chiharakenta** [comment]
例:
```javascript
const clubName = “Among Us”;
const url = “https://tambourine.kibe.la/notes/19541”;
const userIds = [“UR285JW80”];
```

**Comment by shuta13** [comment]
https://github.com/tam-bourine/club-manager/issues/170#issuecomment-785771066

こちらで巻き取ります
