### ISSUE TITLE
ショートカットでも呼び出せるようにしたい

### ISSUE THREAD

**Issue by 75asa** [tam-bourine/club-manager#193]
**Summary/概要**
スラッシュコマンドだと非エンジニアは使いづらいため

**Goal/期待すべき完了条件**

- [ ] ...

**_How/どのようにやるか_**

**Additional context/追記・備考**

**Comment by tk-ozawa** [comment]
超賛成

**Comment by tk-ozawa** [comment]
参考 -> https://slack.dev/bolt-js/ja-jp/concepts#steps

**Comment by 75asa** [comment]
FYI: https://github.com/k-gen/pigeon-message
