### ISSUE TITLE
ローカル開発時に src/index.ts でユーザをメンションするのがノイズなのでアイコンとユーザ名だけにする

### ISSUE THREAD

**Issue by 75asa** [tam-bourine/club-manager#209]
**Summary/概要**
- タイトル通り
- Slack の Mentions & Reactions を活用する人にとってはノイズ
- TLけいさつのようにユーザアイコンとユーザ名にすればいいかな

**Goal/期待すべき完了条件**
- [ ] ローカルサーバー起動した際にメンションされないこと
- [ ] いい感じの BlockKit になってること

**_How/どのようにやるか_**
以下の postMessage() に blocks 追加する
block は 75asa/time-liner のやつとか参考にするといいかも

```typescript
(async () => {
  await app.start(Config.Slack.Bolt.SERVE_PORT);
  console.log(`⚡️ Bolt app is running! on PORT: ${Config.Slack.Bolt.SERVE_PORT}!`);

  if (Config.General.APP_ENV === Config.General.APP_ENV_TYPE.LOCAL) {
    app.client.chat.postMessage({
      token: Config.Slack.BOT_TOKEN,
      text: `<!here> アプリ起動: <@${Config.Slack.Bolt.DEBUG_USER}>`,
      channel: Config.Slack.APPROVAL_CHANNEL_ID,
    });
  }
})();
```

**Additional context/追記・備考**

**Comment by shuta13** [comment]
一旦現行ブランチでは @.here を付けない形でやってもらってます

**Comment by 75asa** [comment]
@shuta13 現行なってないようなんだけどローカルの最新ではってことかな
https://github.com/tam-bourine/club-manager/blob/main/src/index.ts

**Comment by 75asa** [comment]
@shuta13 あとPRで内容話せますと #213

**Comment by shuta13** [comment]
> @shuta13 現行なってないようなんだけどローカルの最新ではってことかな
> https://github.com/tam-bourine/club-manager/blob/main/src/index.ts

そうです、ローカルらしい
