### ISSUE TITLE
README かく

### ISSUE THREAD

**Issue by 75asa** [tam-bourine/club-manager#23]
README 書いたらオッケー

**Comment by chiharakenta** [comment]
GAS
- dev用のスプレッドシートと、各自が使うsandbox用のシートを用意

CloudFunctions for Firebase
- 各自で準備

**Comment by 75asa** [comment]
> dev用のスプレッドシートと、各自が使うsandbox用のシートを用意

ここって今一体型の GAS だよね
分離型でも問題はない？ちょっと気になったので

**Comment by chiharakenta** [comment]
一体型で考えてましたが、確かに分離型でも問題ないですね。
分離型で、シートはdevelop用のシートを用意するだけでもなんとかなりそうです。

開発者全員に、シートへの管理者権限付与して、コードでシートを読み込むときはopenByIdで読み書きするようにすれば行けますね。
https://qiita.com/rf_p/items/47b3154e12c5107b9015

**Comment by chiharakenta** [comment]
@75asa 
ちなみに、GASとシートを分離型にするメリットってなんでしょうか？

**Comment by 75asa** [comment]
> @75asa
> ちなみに、GASとシートを分離型にするメリットってなんでしょうか？

分離型のメリットかー
あ、シートは開発用で分けたいときとかは便利かもですね
シートIDを ScriptProperty とかにして保存したいっていうニーズ
- GAS
  - シートA（開発用）
  - シートB（本番）

**Comment by chiharakenta** [comment]
> 分離型のメリットかー
> あ、シートは開発用で分けたいときとかは便利かもですね
> シートIDを ScriptProperty とかにして保存したいっていうニーズ
> 
> * GAS
>   
>   * シートA（開発用）
>   * シートB（本番）

@75asa 
ありがとうございます！

それでいうと自分の想定では、
- シートA(本番用)
- シートB~(開発用)
- シートC~Z(個人用に複製して用意)
として使うのを想定していたので、
「個人のシートを用意するなら、一体型でも問題ないのではなかろうか。」
と考えたのですが、実際のところ、一体型でも分離型でもどっちでも良いのでしょうか？

**Comment by 75asa** [comment]
どっちでもおk
本番・開発メイン・各々の個人環境の棲み分けがしっかりしてればなんでもいいと思います〜
