### ISSUE TITLE
コーディング規約の設定

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#39]
# Goal
- 合意の取れたコーディング規約の策定
- Wikiにコーディング規約を明記する

# why
- レビューしやすいようにするため
- チーム開発しやすいように

**Comment by chiharakenta** [comment]
@75asa 
JSがキャメルケースなら、 Open APIのkeyもキャメルケースに変更すべきなのでしょうか？
一般的な外部APIがスネークケースで返ってくるものが多いので、今はスネークケースの状態にしてあるのですが...

具体的には、Bolt書いている側で、リクエストを送るときに、スネークケースを書かなければならなくなると、lintやprettierに弾かれてしまうのではないかという懸念があります。

**Comment by 75asa** [comment]
確かにそうですね〜
外部APIとかなら別にいいけど今回ディレクトリ分けて開発するわけですもんね

> 一般的な外部APIがスネークケースで返ってくるものが多いので、今はスネークケースの状態にしてあるのですが...

これは一重に言えないかなって思いました
外部APIかは言及されてないですが、世界的にも コーディングスタイルをどうやって書くかはまちまち、かつもっともポピュラーなのはキャメルという記事もあったので...
なので世間的に多いから...という縛りは少なくとも気にしなくていいと思いました
[参考：Case Styles: Camel, Pascal, Snake, and Kebab Case](https://medium.com/better-programming/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841)

なので、一旦どうやってかくかのコーディングルールは相談して決めてください
ケバブケースとかもあるよう（GoogleやWordPress）

@tamayan 北川さんどう思いますか？

**Comment by tamayan** [comment]
@75asa @chiharakenta jsonのkeyの話をスネークケースかキャメルケースにするかって話であってるかな？個人的な意見としては、パースしたjsonを参照するのにスネークケースでlintにひっかかって都度キャメルケースへの変換が必要なのであればjsonの時点でキャメルケースにしていいんじゃないかなと思います。

**Comment by 75asa** [comment]
> @75asa @chiharakenta jsonのkeyの話をスネークケースかキャメルケースにするかって話であってるかな？個人的な意見としては、パースしたjsonを参照するのにスネークケースでlintにひっかかって都度キャメルケースへの変換が必要なのであればjsonの時点でキャメルケースにしていいんじゃないかなと思います。

@tamayan 認識あってます！ですね、ただベースのコードスタイルどっちか迷ってるんであれば、とどのつまりどっちでもいいよって話なんで、今どれぐらいキャメルでコード書いてるかとかルールをどう設定してるかとか、けどスネークで書きたいだとか...ほんまこれ

**Comment by chiharakenta** [comment]
@75asa 

> ただベースのコードスタイルどっちか迷ってるんであれば、とどのつまりどっちでもいいよって話なんで、

承知しました！
丁寧にお応えいただいて本当にありがとうございます。

どっちでも大丈夫であれば、JS側で決める規約に合わせるようにいたします。

**Comment by chiharakenta** [comment]
@tk-ozawa 
僕と森くんの間でコーディング規約の合意が取れたので、確認して問題なければcloseお願いしたいです！

Airbnbに合わせる方針
https://github.com/tam-bourine/club-manager/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84
