### ISSUE TITLE
コーディング規約に沿ってコードをリファクタ

### ISSUE THREAD

**Issue by Kazu950** [tam-bourine/club-manager#40]
# 何をするか
コーディング規約が確立される以前に書いたコードを規約に沿ってリファクタする。

# 完了条件
- [ ] ESLint、Prettierを実行してコードを規約に沿った記述に変換する。

**Comment by tk-ozawa** [comment]
以下のパッケージを入れる

-  eslint-config-airbnb-base
- eslint-plugin-import
