### ISSUE TITLE
フォーマッターの設定をコーディング規約に合わせる

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#42]
# Goal
[コーディング規約](https://github.com/airbnb/javascript)に合わせてキャメルケースに変更する
参考
- [Wiki](https://github.com/tam-bourine/club-manager/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84)

**Comment by tk-ozawa** [comment]
👀

**Comment by tk-ozawa** [comment]
確認
