### ISSUE TITLE
ディレクトリ構成をGAS用とBolt用で分割

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#44]
現段階で影響のあるプルリクエストを全てマージしてから着手

# Goal
- [ ] ルートディレクトリから、gasフォルダーとboltフォルダー(名前は小澤君の任意で変更)が作成されている
- [ ] ファイル分けがされている

# Why
- 現状、どれがGAS用のディレクトリで、どれがBolt用のディレクトリか分かりにくいから
- 後から入ってきたメンバーがディレクトリ構成を理解しやすくするため

**Comment by tk-ozawa** [comment]
これ先しますー
