### ISSUE TITLE
創部申請を送信する際に発生する多重リクエストによるエラーの解消

### ISSUE THREAD

**Issue by Kazu950** [tam-bourine/club-manager#52]
# Goal
- [ ] 創部申請の送信時に発生するエラーの解消

# 備考
- 現状、ワークフローから創部申請を送信するとFunctionsではデータを正常に受け取ることができている。
- データを受け取ることはできているが多重リクエストが発生してしまいエラーがでている。

**Comment by 75asa** [comment]
FaaS のレスポンスが遅いからなのかな🤔
コールドスタートしてるのでワーミングするとか？

**Comment by Kazu950** [comment]
調べても分からなかったのでワーミングの
意味教えていただいてもいいですか？🙇‍♂️

**Comment by 75asa** [comment]
こちらです！
https://github.com/yuraki148/newChannelBot/issues/6#issuecomment-741337056

**Comment by Kazu950** [comment]
ありがとうございます！
いったん、千原くんが多重リクエストのエラー処理について
LikeLikeを開発する際に実装した経験があると言っていたので
詳しく聞いてみようと思います。
それで無理そうならワーミングしようと思います！
