### ISSUE TITLE
GAS key,value型のオブジェクトを配列に変換する関数を追加

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#68]
# Goal
src/gas/utils/utils.jsに
次の要件を満たす関数を作成

- objectToArray(object)
- return values: array

例:
```javascript
let object = {
  id: 1,
  name: '千原',
  age: 22
}
let values = objectToArray(object);
console.log(values);
}
```
出力結果
```javascript
[1, '千原', 22]
```

# Why
- シートにデータを挿入する際に利用する、appendRowメソッドの引数に配列を渡す必要があるから
- https://developers.google.com/apps-script/reference/spreadsheet/sheet#appendRow(Object)

**Comment by tk-ozawa** [comment]
lodashの_.values(obj);で良さそう

**Comment by tk-ozawa** [comment]
こんなことをしなくても`Object.values(user)`でできるやんという報告

**Comment by chiharakenta** [comment]
初めて知りました...
ありがとうございます！
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values
