### ISSUE TITLE
ワークフローから情報を受け取るコードを作成

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#7]
Bolt for JSを利用

**Comment by 75asa** [comment]
> ワークフローから情報を受け取るコードを作成 #7

情報ってのがスコープ広すぎるので中々このイシューがクローズできないかなって思いました

@chiharakenta @Kazu950 
先ずは 情報 ていう抽象度合いが強い単位ではなく、例えば
「ワークフローでフォームからユーザのプロフィールを受け取って他のチャンネルに転送するScriptをかく」
のような（適宜変えてください）具体的にやることを明示・もしくはタイトルにかくのが望ましいです
またイシューには必ず ***何をやったら完了するかっていう完了条件を明記しておくとチケットがサクサク閉じれます
