### ISSUE TITLE
GAS 入部申請

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#72]
# Goal
Open APIの「参加申請」の通りにエンドポイントを実装する
![image](https://user-images.githubusercontent.com/39648121/103125492-94e25400-46ce-11eb-9e35-18271c43eb63.png)
![image](https://user-images.githubusercontent.com/39648121/103125496-9ca1f880-46ce-11eb-9d71-290f328e845e.png)

**Comment by shuta13** [comment]
https://github.com/tam-bourine/club-manager/issues/145 こっちに移行するので close
