### ISSUE TITLE
既存のダイアグラムの詳細化

### ISSUE THREAD

**Issue by tk-ozawa** [tam-bourine/club-manager#82]
## What?
- `SlackApp --> スプレッドシート`等の項を具体的にしていただきたいお気持ち
  - GASレイヤーとBoltレイヤーを足した方が良さそうじゃないですか説

## Why?
- 概要が欲しいため
- 後から入った人が専門用語に振り回されないようにするため

**Comment by tk-ozawa** [comment]
@75asa 
森さんと話してて出た案なんですがいかがでしょうか

**Comment by 75asa** [comment]
いんじゃないでしょうか！
