### ISSUE TITLE
TypeScript にする!

### ISSUE THREAD

**Issue by 75asa** [tam-bourine/club-manager#83]
**Summary/概要**
TS 入れる

**Goal/期待すべき完了条件**
- [x] *.js -> *.ts になってること

**_How/どのようにやるか_**
- ファイルが少ないうちに TS 化しちゃう
- [Google App ScriptをTypeScriptとClass構文で書く - 環境導入](https://blog.solunita.net/posts/lean-to-develop-google-app-script-with-typescript-class-setup/)
- [GASをclasp（CLIツール）+ TypeScriptでローカルで開発する](https://panda-program.com/posts/clasp-typescript)
- [TypescriptでGASを書いていると、HttpMethodでerror TS2345が出る](https://ja.stackoverflow.com/questions/66761/typescript%E3%81%A7gas%E3%82%92%E6%9B%B8%E3%81%84%E3%81%A6%E3%81%84%E3%82%8B%E3%81%A8-httpmethod%E3%81%A7error-ts2345%E3%81%8C%E5%87%BA%E3%82%8B)

**Additional context/追記・備考**

**Comment by chiharakenta** [comment]
一旦、Boltは考えずに、GASの方だけ考える

**Comment by chiharakenta** [comment]
GASは問題なさそうなので、全体の移行について考える

**Comment by 75asa** [comment]
GAS by clasp で TS 使う場合
https://github.com/google/clasp/blob/master/docs/typescript.md

**Comment by 75asa** [comment]
GAS をローカルで色々するとき ESModule つかいたいなーてとき
http://aligach.net/diary/20201112.html

**Comment by chiharakenta** [comment]
TypeScript導入の理由(by 名護さん)
- 型定義によって、コーディングをしやすくする
- [デファクトスタンダード](https://ja.wikipedia.org/wiki/%E3%83%87%E3%83%95%E3%82%A1%E3%82%AF%E3%83%88%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%80%E3%83%BC%E3%83%89#:~:text=%E3%83%87%E3%83%95%E3%82%A1%E3%82%AF%E3%83%88%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%80%E3%83%BC%E3%83%89%EF%BC%88%E8%8B%B1%E8%AA%9E%3A%20de%20facto,%E3%81%AB%E3%81%AF%E3%80%8D%E3%82%92%E6%84%8F%E5%91%B3%E3%81%99%E3%82%8B%E3%80%82)に合わせる
    - 検索がしやすい
    - Node.jsをそのまま書いている人よりも、TypeScriptで書いている人の方が多いし、今後も多くなる。
    - JSで検索すると古い書き方をそのまま書いている人も多いけど、TypeScriptだとES6（最近の記法）移行の記法で書いている記事がほとんどなので、調べてそのまま使いやすい。(by 小澤さん)
- 今回の学習を元に、別のTypeScriptを用いた社内ツールプロジェクトにも入りやすくする

以上のメリットと、学習コストを天秤にかけた結果として、TypeScriptを導入することに。
