### ISSUE TITLE
READMEを仕様変更後の最新版に対応

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#89]
**Summary/概要**
TypeScriptやESLintのコマンドを追加したので、READMEに追記する。

**Goal/期待すべき完了条件**
READMEの手順に沿って実行したときに
- [ ] GASでTypeScriptを書いて、ESLintがエラーを吐く
    - 参考: #103
- [ ] GASでTypeScriptを書いて、clasp pushでpushできる
    - [ ] スプレッドシートの画像を更新する
- [ ] BoltでTypeScriptを書いて、ESLintがエラーを吐く
- [ ] BoltでTypeScriptを書いて、npm run build:firebase コマンドでjsにコンパイルできる

**_How/どのようにやるか_**

**Additional context/追記・備考**

**Comment by chiharakenta** [comment]
#83 完了後に着手

**Comment by chiharakenta** [comment]
README中のスプレッドシートの画像も変更
![image](https://user-images.githubusercontent.com/39648121/105829321-92458800-6007-11eb-9d2e-3d5a1ee2e64e.png)

**Comment by 75asa** [comment]
firebase けしたのでそれも反映おな

**Comment by shuta13** [comment]
https://github.com/tam-bourine/club-manager/issues/183

**Comment by shuta13** [comment]
firebase の項目消し飛ばしこの issue でやります
