### ISSUE TITLE
build:firebaseで検出するエラーとESLintで検出するエラーを一致させる

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-manager#90]
**Summary/概要**
現状
- ESLintでは、importが何故かエラーになる
    - ![image](https://user-images.githubusercontent.com/39648121/104878750-dbf6f880-599f-11eb-8a44-c06ef3b7d347.png)
- build:firebaseでは、ESLintで検出するエラーは出てこない

**Goal/期待すべき完了条件**

- [ ] npm run lintでsrc/functionsフォルダー内のエラーを検出できる
    - .eslintignoreからsrc/functionsの記述を削除する
- [ ] build:firebaseで検出するエラーとESLintで検出するエラーを一致させる

**_How/どのようにやるか_**

**Additional context/追記・備考**

**Comment by tk-ozawa** [comment]
自分の環境だとエラー出ないので不思議

**Comment by chiharakenta** [comment]
環境依存っぽかったのでclose
